# Generated by Django 5.2.17 on 2026-08-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='renewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='crm.servicerecord', verbose_name='Продлена записью'),
        ),
    ]
