# Generated by Django 5.2.17 on 2026-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_servicerecord_renewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('insurance', 'Страховка'), ('tinting', 'Тонировка'), ('power_of_attorney', 'Доверенность'), ('other', 'Прочее')], max_length=32, unique=True, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'настройка уведомления',
                'verbose_name_plural': 'настройки уведомлений',
                'ordering': ['service_type'],
            },
        ),
    ]
