# Generated by Django 5.2.17 on 2026-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_servicenotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenotificationsetting',
            name='warning_days',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Предупреждать за, дней'),
        ),
    ]
