# Generated by Django 5.2.17 on 2026-08-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_servicenotificationsetting_warning_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenotificationsetting',
            name='service_type',
            field=models.CharField(choices=[('insurance', 'Страховка'), ('tinting', 'Тонировка'), ('power_of_attorney', 'Доверенность'), ('other', 'Прочие услуги')], max_length=32, unique=True, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('insurance', 'Страховка'), ('tinting', 'Тонировка'), ('power_of_attorney', 'Доверенность'), ('other', 'Прочие услуги')], max_length=32, verbose_name='Тип услуги'),
        ),
    ]
