# Generated by Django 5.2.17 on 2026-08-14 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_servicenotificationsetting_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта вручную'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_services', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл сотрудник'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('elsewhere', 'Оформлено в другом месте'), ('declined', 'Клиент отказался'), ('not_relevant', 'Услуга больше не актуальна'), ('other', 'Другая причина')], max_length=32, verbose_name='Причина закрытия'),
        ),
    ]
