# Generated by Django 5.2.17 on 2026-08-14 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_servicerecord_closed_at_servicerecord_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['service_type', 'expires_on'], name='service_type_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['closed_at', 'expires_on'], name='service_closed_expiry_idx'),
        ),
    ]
