# Generated by Django 5.2.17 on 2026-08-15 13:49

from django.db import migrations, models


def translate_document_recipients(apps, schema_editor):
    ServiceRecord = apps.get_model('crm', 'ServiceRecord')
    translations = {
        'ota': 'father',
        'ona': 'mother',
        'er': 'husband',
        'xotin': 'wife',
        'aka': 'brother',
        'uka': 'brother',
    }
    for old_value, new_value in translations.items():
        ServiceRecord.objects.filter(document_recipient=old_value).update(
            document_recipient=new_value
        )
    ServiceRecord.objects.exclude(
        document_recipient__in=['', *translations.values()]
    ).update(document_recipient='')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_servicerecord_document_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenotificationsetting',
            name='service_type',
            field=models.CharField(choices=[('avtoraqam', 'Avtoraqam'), ('insurance', 'Страховка'), ('tinting', 'Тонировка'), ('power_of_attorney', 'Доверенность'), ('other', 'Прочие услуги')], max_length=32, unique=True, verbose_name='Тип услуги'),
        ),
        migrations.RunPython(translate_document_recipients, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicerecord',
            name='document_recipient',
            field=models.CharField(blank=True, choices=[('owner', 'Владелец авто'), ('father', 'Отец'), ('mother', 'Мать'), ('husband', 'Муж'), ('wife', 'Жена'), ('brother', 'Брат')], max_length=16, verbose_name='Кому переданы документы'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('avtoraqam', 'Avtoraqam'), ('insurance', 'Страховка'), ('tinting', 'Тонировка'), ('power_of_attorney', 'Доверенность'), ('other', 'Прочие услуги')], max_length=32, verbose_name='Тип услуги'),
        ),
    ]
