# Generated by Django 5.2.17 on 2026-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_servicenotificationsetting_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
