# Generated by Django 5.2.17 on 2026-08-16 08:10

from django.db import migrations, models


def combine_relative_recipients(apps, schema_editor):
    ServiceRecord = apps.get_model('crm', 'ServiceRecord')
    ServiceRecord.objects.filter(
        document_recipient__in=['father', 'mother', 'husband', 'wife', 'brother']
    ).update(document_recipient='relative')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_servicerecord_expires_on'),
    ]

    operations = [
        migrations.RunPython(combine_relative_recipients, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicerecord',
            name='document_recipient',
            field=models.CharField(blank=True, choices=[('owner', 'Владелец авто'), ('relative', 'Родственник'), ('stranger', 'Незнакомый')], max_length=16, verbose_name='Кому переданы документы'),
        ),
    ]
