# Generated by Django 5.2.17 on 2026-08-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_appearancesetting_color_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='crm.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'избранный клиент',
                'verbose_name_plural': 'избранные клиенты',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'client'), name='unique_user_favorite_client')],
            },
        ),
    ]
