# Generated by Django 5.2.17 on 2026-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_clientfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('elsewhere', 'Оформлено в другом месте'), ('vehicle_sold', 'Машина была продана'), ('declined', 'Клиент отказался'), ('not_relevant', 'Услуга больше не актуальна'), ('other', 'Другая причина')], max_length=32, verbose_name='Причина закрытия'),
        ),
    ]
